### PR TITLE
added flow files "--no-list" and "--error-on-missing" options

### PR DESCRIPTION
**Pull request by JeriXNet**
Added stated option to flow status menu.
Maybe these options can be useful for others?

### CODE REVIEW

**Comment by ruby0x1** [comment]
Thanks for this - but I won't pull it in immediately.

As you can see I was working on options for some of the flow commands already (clean, etc) but there are just too many for it to work from this drop down. It needs to be changed into a more legible form. If you have 10+ options showing it becomes difficult to quickly read and choose the right thing, and is overwhelming.

I think that a better option is required first, before adding options in. There are quite a lot that I want to add in there, and there will not be enough space, so it has to be rethought out first :)

**Comment by JeriXNet** [comment]
Ok, I see it'll take some time and thinking of.
Btw, I was thinking about implementing all flow options saving in sublime config but stopped for now.
How do you think, Is it hard to implement those saving? Will it worth it?
Maybe I'll do it :)

**Comment by ruby0x1** [comment]
There is a very specific workflow that I have in mind that I am working toward, I will make a proper list and we can go from there? I feel like that just adding features without direction will lead somewhere less good for the goals here.

I am investigating options for handling a custom panel, if that's possible to do with rendering somehow that would be the first thing I would research.

**Comment by JeriXNet** [comment]
Ok. I just want you to know that I want to help if you find proper direction for development.

**Pull request closed without merging**
